
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length: 200
opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping
  - yoda_condition
